### ISSUE TITLE
いろいろな言語ボタンのリンク間違い

### ISSUE THREAD

**Issue by 610t** [teraschool/teraschool.github.io#136]
Topページのindex.htmlの84行目の「いろいろな言語」ボタンのリンク先が/languages/であるべきが/language/と間違っています。
間違い: {% include parts/button.html href="/language/" class="keyVisual__linkButton" content="いろいろな言語" %}
正しい: {% include parts/button.html href="/languages/" class="keyVisual__linkButton" content="いろいろな言語" %}

**Comment by kwaka1208** [comment]
指摘、ありがとうございます。トップの大事なリンクを盛大にミスってましたね。 ^ ^;
